version: '2'
services:
    cdb_grade-app:
        image: cdb_grade
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cdb_grade-mysql:3306/cdb_grade?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cdb_grade-mysql:
        extends:
            file: mysql.yml
            service: cdb_grade-mysql
